events {
}

http{ 
    server {
        #SSL Config
        listen 443 ssl;
        ssl_protocols TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        root /var/www/wordpress;
        index index.php index.html index.htm;
        server_name efoyer.42.fr;

        location / {
        try_files $uri $uri/ =404;
        }


        # location ~ \.php$ { # Pour toute les requetes php
        #     include snippets/fastcgi-php.conf; # charge le fichier
        #     fastcgi_pass wordpress:9000; # transmet la requete sur le port 9000
        # }  A mettre en commentaire le temps que le container wordpress est pas installer
    }
}

